insert into books(title,
                  author_first_name,
                  author_last_name,
                  isbn,
                  publisher,
                  category)
values ('The Hitchhiker''s Guide to the Galaxy',
        'Douglas',
        'Adams',
        '9780345391803',
        'Del Rey',
        'FICTION'),
       ('The Name of the Wind',
        'Patrick',
        'Rothfuss',
        '9780756404741',
        'DAW Books',
        'FICTION'),
       ('Thinking, Fast and Slow',
        'Daniel',
        'Kahneman',
        '9780374533557',
        'Farrar, Straus and Giroux',
        'NON_FICTION'),
       ('The Gruffalo',
        'Julia',
        'Donaldson',
        '9780333905581',
        'Macmillan Children''s Books',
        'CHILDRENS_BOOK'),
       ('Where the Crawdads Sing',
        'Delia',
        'Owens',
        '9780735219090',
        'G.P. Putnam''s Sons',
        'ADULTS_BOOK'),
       ('Cosmos',
        'Carl',
        'Sagan',
        '9780345539434',
        'Ballantine Books',
        'SCIENCE'),
       ('A People''s History of the United States',
        'Howard',
        'Zinn',
        '9780060528379',
        'Harper Perennial',
        'HISTORY');

insert into book_copies(book_id, follow_number, status)
values (1, 1, 'AVAILABLE'),
       (1, 2, 'ON_LOAN'),
       (2, 1, 'AVAILABLE'),
       (3, 1, 'DAMAGED'),
       (3, 2, 'AVAILABLE'),
       (3, 3, 'ON_LOAN'),
       (3, 4, 'AVAILABLE'),
       (3, 5, 'AVAILABLE'),
       (4, 1, 'AVAILABLE'),
       (5, 1, 'MISSING'),
       (6, 1, 'AVAILABLE'),
       (7, 1, 'IN_REPAIR');